### ISSUE TITLE
Room and Message Avatars

### ISSUE THREAD

**Issue by r0kk3rz** [Sailbook/harbour-matrix#11]
Since we've already had some duplicate work on this I thought I should write up the current situation.

On the Message side, I've added avatar URLs to the decoration role, so in QML if you have something like this on the view that should be all you need
`Image {
source: decoration
}`

Since you cant just display a QPixMap straight into QML Land you need to use an Image Provider class that takes a `image://provider/url` QUrl

I've added an ImageProvider class that takes a reformatted Matrix resource URL and does all the fetching and resizing for you taking a `image://mxc/source/id` style path translated from `mxc://source/id`:
https://github.com/Sailbook/harbour-matrix/blob/master/src/models/messageeventmodel.cpp#L306

The same kind of thing should be possible to use with Room Avatars as well as any Images in posts

**Comment by AlmAck** [comment]
I prepared something here, is not finished yet, is more a concept then a final work:
https://github.com/AlmAck/harbour-matrix/commit/c1ac81faa45569c228c4811b97f67ff749b209a9

I like the bubble avatar currently implemented, I wanted to do implement the images in the same way. Btw, Why use decoration instead of a proper defined element? like avatar?

Look like this:
![20171119203817](https://user-images.githubusercontent.com/203615/32994620-35fb1dea-cd6a-11e7-9dd4-95ab113e3863.jpg | width=48)

**Comment by Sailbook** [comment]
Thanks, that looks verry nice !

**Comment by Sailbook** [comment]
Fixed
